version: "3.8"

services:
  api:
    build: ./app
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/storage
    depends_on:
      - omnizart

  omnizart:
    build: ./omnizart
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ./storage:/storage
