services:
  fastapi:
    container_name: fastapi
    image: ssafya205/beatween-fastapi:latest
    env_file:
      - ./fastapi/.env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/storage
    depends_on:
      - omnizart
  
  omnizart:
    container_name: omnizart
    image: ssafya205/beatween-flask:latest
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ./storage:/storage
